regen
git-svn-id: file:///home/dev/edacious/trunk@92 2ffb977e-9902-0410-a00a-94b404125a2c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6,7 +6,7 @@
 # To regenerate this file, get the latest BSDbuild release from
 # http://hypertriton.com/bsdbuild/, and use the command:
 #
-#      configure.in | mkconfigure > configure
+#     $ cat configure.in | mkconfigure > configure
 #
 # Copyright (c) 2001-2007 Hypertriton, Inc. <http://hypertriton.com/>
 # All rights reserved.
@@ -131,6 +131,7 @@ echo "    --srcdir                       Source tree for concurrent build [.]"
 echo "    --help                         Display this message"
 echo "    --enable-nls                   Native Language Support [no]"
 echo "    --with-gettext                 Use gettext tools (msgmerge, ...) [check]"
+echo "    --with-libtool                 Specify path to libtool [check]"
 echo "    --with-manpages                Manual pages (-mdoc) [yes]"
 echo "    --with-docs                    Printable docs (-me/tbl/eqn/pic/refer) [no]"
 echo "    --enable-debug                 Include debugging code [no]"
@@ -141,15 +142,19 @@ exit 1
 fi
 
 MACHINE=`uname -m 2>/dev/null` || MACHINE=unknown
-RELEASE=`uname -r 2>/dev/null` || RELEASE=unknown
+OSRELEASE=`uname -r 2>/dev/null` || OSRELEASE=unknown
 SYSTEM=`uname -s 2>/dev/null` || SYSTEM=unknown
-HOST="$SYSTEM-$RELEASE-$MACHINE"
+HOST="$SYSTEM-$OSRELEASE-$MACHINE"
 echo "Host: $HOST"
 
 echo "# File generated by configure script (BSDbuild 2.1)." > Makefile.config
 echo "Machine: $MACHINE" > config.log
-echo "Release: $RELEASE" >> config.log
+echo "Release: $OSRELEASE" >> config.log
 echo "System: $SYSTEM" >> config.log
+for arg
+do
+	echo "Argument: $arg" >> config.log
+done
 mkdir config 1>/dev/null 2>&1
 
 HAVE_MANDOC="no"
@@ -219,6 +224,43 @@ fi
 echo "ENABLE_NLS=${ENABLE_NLS}" >> Makefile.config
 echo "HAVE_GETTEXT=${HAVE_GETTEXT}" >> Makefile.config
 
+echo -n "checking for libtool..."
+LIBTOOL_BUNDLED="no"
+if [ "${with_libtool}" != "" ]; then
+	LIBTOOL=${with_libtool}
+else
+	ltool=""
+	for path in `echo $PATH | sed 's/:/ /g'`; do
+		if [ -x "${path}/libtool" ]; then
+			ltool=${path}/libtool
+		fi
+	done
+	if [ "${ltool}" != "" ]; then
+		${ltool} --version 1>/dev/null 2>&1
+		if [ $? == 0 ]; then
+			LIBTOOL=${ltool}
+		else
+			LIBTOOL=\${TOP}/mk/libtool/libtool
+			LIBTOOL_BUNDLED="yes"
+		fi
+	else
+		LIBTOOL=\${TOP}/mk/libtool/libtool
+		LIBTOOL_BUNDLED="yes"
+	fi
+fi
+if [ "${LIBTOOL_BUNDLED}" = "yes" ]; then
+	echo "yes (bundled)"
+else
+	grep ^VERSION=1.5 "${LIBTOOL}" 1>/dev/null 2>&1
+	if [ $? == 0 ]; then
+		echo "yes (GNU libtool 1.5)"
+		echo "LIBTOOLFLAGS=-prefer-pic" >> Makefile.config
+	else
+		echo "yes (GNU libtool)"
+	fi
+fi
+echo "LIBTOOL=${LIBTOOL}" >> Makefile.config
+
 echo "PREFIX?=${PREFIX}" >> Makefile.config
 echo "#ifndef PREFIX" > config/prefix.h
 echo "#define PREFIX \"${PREFIX}\"" >> config/prefix.h
@@ -266,33 +308,33 @@ else
 	echo "#endif /* SYSCONFDIR */" >> config/sysconfdir.h
 fi
 
-VERSION="\"09152007\""
+VERSION="09152007"
 echo "#ifndef VERSION" > config/version.h
-echo "#define VERSION" $VERSION >> config/version.h
+echo "#define VERSION \"$VERSION\"" >> config/version.h
 echo "#endif" >> config/version.h
 SHAREDIR="$PREFIX/share/agar-eda"
 echo "SHAREDIR=$SHAREDIR" >> Makefile.config
 SHAREDIR="\"$PREFIX/share/agar-eda\""
 echo "#ifndef SHAREDIR" > config/sharedir.h
-echo "#define SHAREDIR" $SHAREDIR >> config/sharedir.h
+echo "#define SHAREDIR \"$SHAREDIR\"" >> config/sharedir.h
 echo "#endif" >> config/sharedir.h
 TTFDIR="$PREFIX/share/agar-eda/fonts"
 echo "TTFDIR=$TTFDIR" >> Makefile.config
 TTFDIR="\"$PREFIX/share/agar-eda/fonts\""
 echo "#ifndef TTFDIR" > config/ttfdir.h
-echo "#define TTFDIR" $TTFDIR >> config/ttfdir.h
+echo "#define TTFDIR \"$TTFDIR\"" >> config/ttfdir.h
 echo "#endif" >> config/ttfdir.h
 LIBDIR="$PREFIX/lib/agar-eda"
 echo "LIBDIR=$LIBDIR" >> Makefile.config
 LIBDIR="\"$PREFIX/lib/agar-eda\""
 echo "#ifndef LIBDIR" > config/libdir.h
-echo "#define LIBDIR" $LIBDIR >> config/libdir.h
+echo "#define LIBDIR \"$LIBDIR\"" >> config/libdir.h
 echo "#endif" >> config/libdir.h
 INCLDIR="$PREFIX/include/agar-eda"
 echo "INCLDIR=$INCLDIR" >> Makefile.config
 INCLDIR="\"$PREFIX/include/agar-eda\""
 echo "#ifndef INCLDIR" > config/incldir.h
-echo "#define INCLDIR" $INCLDIR >> config/incldir.h
+echo "#define INCLDIR \"$INCLDIR\"" >> config/incldir.h
 echo "#endif" >> config/incldir.h
 echo -n "checking for a usable C compiler..."
 echo -n "checking for a usable C compiler..." >> config.log
@@ -500,6 +542,72 @@ HAVE_NONNULL_ATTRIBUTE="no"
 echo "HAVE_NONNULL_ATTRIBUTE=$HAVE_NONNULL_ATTRIBUTE" >> Makefile.config
 echo "#undef HAVE_NONNULL_ATTRIBUTE" > config/have_nonnull_attribute.h
 fi;
+echo -n "checking __aligned__ attribute..."
+echo -n "checking __aligned__ attribute..." >> config.log
+cat << EOT > conftest.c
+int main(int argc, char *argv[])
+{
+	struct s1 { int x,y,z; } __attribute__ ((aligned(16)));
+	return (0);
+}
+
+EOT
+compile="ok"
+echo "$CC $CFLAGS $TEST_CFLAGS -Wall -Werror -o conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -Wall -Werror -o conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed ($?)" >> config.log
+	compile="failed"
+fi
+rm -f conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_ALIGNED_ATTRIBUTE="yes"
+echo "HAVE_ALIGNED_ATTRIBUTE=$HAVE_ALIGNED_ATTRIBUTE" >> Makefile.config
+echo "#ifndef HAVE_ALIGNED_ATTRIBUTE" > config/have_aligned_attribute.h
+echo "#define HAVE_ALIGNED_ATTRIBUTE \"$HAVE_ALIGNED_ATTRIBUTE\"" >> config/have_aligned_attribute.h
+echo "#endif" >> config/have_aligned_attribute.h
+else
+echo "no"
+echo "no" >> config.log
+HAVE_ALIGNED_ATTRIBUTE="no"
+echo "HAVE_ALIGNED_ATTRIBUTE=$HAVE_ALIGNED_ATTRIBUTE" >> Makefile.config
+echo "#undef HAVE_ALIGNED_ATTRIBUTE" > config/have_aligned_attribute.h
+fi;
+echo -n "checking __packed__ attribute..."
+echo -n "checking __packed__ attribute..." >> config.log
+cat << EOT > conftest.c
+int main(int argc, char *argv[])
+{
+	struct s1 { char c; int x,y,z; } __attribute__ ((packed));
+	return (0);
+}
+
+EOT
+compile="ok"
+echo "$CC $CFLAGS $TEST_CFLAGS -Wall -Werror -o conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -Wall -Werror -o conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed ($?)" >> config.log
+	compile="failed"
+fi
+rm -f conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_PACKED_ATTRIBUTE="yes"
+echo "HAVE_PACKED_ATTRIBUTE=$HAVE_PACKED_ATTRIBUTE" >> Makefile.config
+echo "#ifndef HAVE_PACKED_ATTRIBUTE" > config/have_packed_attribute.h
+echo "#define HAVE_PACKED_ATTRIBUTE \"$HAVE_PACKED_ATTRIBUTE\"" >> config/have_packed_attribute.h
+echo "#endif" >> config/have_packed_attribute.h
+else
+echo "no"
+echo "no" >> config.log
+HAVE_PACKED_ATTRIBUTE="no"
+echo "HAVE_PACKED_ATTRIBUTE=$HAVE_PACKED_ATTRIBUTE" >> Makefile.config
+echo "#undef HAVE_PACKED_ATTRIBUTE" > config/have_packed_attribute.h
+fi;
 echo -n "checking for long double..."
 echo -n "checking for long double..." >> config.log
 cat << EOT > conftest.c
@@ -522,19 +630,53 @@ if [ $? != 0 ]; then
 fi
 rm -f conftest conftest.c
 if [ "${compile}" = "ok" ]; then
-	echo "ok" >> config.log
-	echo "#ifndef HAVE_LONG_DOUBLE" > config/have_long_double.h
-echo "#define HAVE_LONG_DOUBLE" $HAVE_LONG_DOUBLE >> config/have_long_double.h
+echo "yes"
+echo "yes" >> config.log
+HAVE_LONG_DOUBLE="yes"
+echo "#ifndef HAVE_LONG_DOUBLE" > config/have_long_double.h
+echo "#define HAVE_LONG_DOUBLE \"$HAVE_LONG_DOUBLE\"" >> config/have_long_double.h
 echo "#endif" >> config/have_long_double.h
-
-	HAVE_LONG_DOUBLE="yes"
-	echo "yes"
 else
-    echo "#undef HAVE_LONG_DOUBLE" > config/have_long_double.h
+echo "no"
+echo "no" >> config.log
+HAVE_LONG_DOUBLE="no"
+echo "#undef HAVE_LONG_DOUBLE" > config/have_long_double.h
+fi;
+echo -n "checking for long long..."
+echo -n "checking for long long..." >> config.log
+cat << EOT > conftest.c
+int
+main(int argc, char *argv[])
+{
+	long long ll = 0.0;
+	unsigned long long ull = 0.0;
+	ll = 1.0;
+	ull = 1.0;
+	return (0);
+}
 
-	HAVE_LONG_DOUBLE="no"
-	echo "no"
+EOT
+compile="ok"
+echo "$CC $CFLAGS $TEST_CFLAGS -o conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -o conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed ($?)" >> config.log
+	compile="failed"
 fi
+rm -f conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_LONG_LONG="yes"
+echo "#ifndef HAVE_LONG_LONG" > config/have_long_long.h
+echo "#define HAVE_LONG_LONG \"$HAVE_LONG_LONG\"" >> config/have_long_long.h
+echo "#endif" >> config/have_long_long.h
+else
+echo "no"
+echo "no" >> config.log
+HAVE_LONG_LONG="no"
+echo "#undef HAVE_LONG_LONG" > config/have_long_long.h
+fi;
 echo -n "checking for cygwin environment..."
 echo -n "checking for cygwin environment..." >> config.log
 cat << EOT > conftest.c
@@ -660,6 +802,7 @@ echo -n "checking whether Agar works..."
 echo -n "checking whether Agar works..." >> config.log
 cat << EOT > conftest.c
 #include <agar/core.h>
+#include <agar/gui.h>
 
 int
 main(int argc, char *argv[])
@@ -745,8 +888,8 @@ int main(int argc, char *argv[]) {
 }
 
 EOT
-echo "$CC $CFLAGS $TEST_CFLAGS ${AGAR_CFLAGS} ${AGAR_SC_CFLAGS} -o conftest conftest.c ${AGAR_SC_LIBS} ${AGAR_LIBS}" >>config.log
-$CC $CFLAGS $TEST_CFLAGS ${AGAR_CFLAGS} ${AGAR_SC_CFLAGS} -o conftest conftest.c ${AGAR_SC_LIBS} ${AGAR_LIBS} 2>>config.log
+echo "$CC $CFLAGS $TEST_CFLAGS ${AGAR_SC_CFLAGS} ${AGAR_CFLAGS} -o conftest conftest.c ${AGAR_SC_LIBS} ${AGAR_LIBS}" >>config.log
+$CC $CFLAGS $TEST_CFLAGS ${AGAR_SC_CFLAGS} ${AGAR_CFLAGS} -o conftest conftest.c ${AGAR_SC_LIBS} ${AGAR_LIBS} 2>>config.log
 if [ $? == 0 ]; then
 echo "yes"
 echo "yes" >> config.log
@@ -836,8 +979,8 @@ int main(int argc, char *argv[]) {
 }
 
 EOT
-echo "$CC $CFLAGS $TEST_CFLAGS ${AGAR_CFLAGS} ${AGAR_VG_CFLAGS} -o conftest conftest.c ${AGAR_LIBS} ${AGAR_VG_LIBS}" >>config.log
-$CC $CFLAGS $TEST_CFLAGS ${AGAR_CFLAGS} ${AGAR_VG_CFLAGS} -o conftest conftest.c ${AGAR_LIBS} ${AGAR_VG_LIBS} 2>>config.log
+echo "$CC $CFLAGS $TEST_CFLAGS ${AGAR_VG_CFLAGS} ${AGAR_CFLAGS} -o conftest conftest.c ${AGAR_VG_LIBS} ${AGAR_LIBS}" >>config.log
+$CC $CFLAGS $TEST_CFLAGS ${AGAR_VG_CFLAGS} ${AGAR_CFLAGS} -o conftest conftest.c ${AGAR_VG_LIBS} ${AGAR_LIBS} 2>>config.log
 if [ $? == 0 ]; then
 echo "yes"
 echo "yes" >> config.log
@@ -930,8 +1073,8 @@ int main(int argc, char *argv[]) {
 }
 
 EOT
-echo "$CC $CFLAGS $TEST_CFLAGS ${AGAR_CFLAGS} ${AGAR_DEV_CFLAGS} -o conftest conftest.c ${AGAR_LIBS} ${AGAR_DEV_LIBS}" >>config.log
-$CC $CFLAGS $TEST_CFLAGS ${AGAR_CFLAGS} ${AGAR_DEV_CFLAGS} -o conftest conftest.c ${AGAR_LIBS} ${AGAR_DEV_LIBS} 2>>config.log
+echo "$CC $CFLAGS $TEST_CFLAGS ${AGAR_DEV_CFLAGS} ${AGAR_CFLAGS} -o conftest conftest.c ${AGAR_DEV_LIBS} ${AGAR_LIBS}" >>config.log
+$CC $CFLAGS $TEST_CFLAGS ${AGAR_DEV_CFLAGS} ${AGAR_CFLAGS} -o conftest conftest.c ${AGAR_DEV_LIBS} ${AGAR_LIBS} 2>>config.log
 if [ $? == 0 ]; then
 echo "yes"
 echo "yes" >> config.log
@@ -1002,9 +1145,9 @@ echo "CFLAGS=$CFLAGS" >> Makefile.config
 fi
 if [ "${enable_edition}" != "no" ]
  then
-EDITION=1
+EDITION="1"
 echo "#ifndef EDITION" > config/edition.h
-echo "#define EDITION" $EDITION >> config/edition.h
+echo "#define EDITION \"$EDITION\"" >> config/edition.h
 echo "#endif" >> config/edition.h
 else
 echo "#undef EDITION" > config/edition.h
