set LIB_MODULE=Yes on libsources, libmacro and libgeneric
git-svn-id: file:///home/dev/edacious/trunk@533 2ffb977e-9902-0410-a00a-94b404125a2c

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -134,6 +134,17 @@ else
 	HUNDEF(EXPR_DEBUG)
 fi
 
+# Enable NLS if requested explicitely.
+if [ "${enable_nls}" = "yes" ]; then
+	CHECK(gettext, 0, ${prefix_gettext})
+	if [ "${HAVE_GETTEXT}" != "yes" ]; then
+		echo "*"
+		echo "* --enable-nls was given but gettext was not found."
+		echo "*"
+		exit 1
+	fi
+fi
+
 # Set up configure script output.
 C_INCPREP($BLD/include/edacious)
 C_INCDIR($BLD/include)
